@startmindmap


<style>
node {
    Padding 12
    RoundCorner 32
    MaximumWidth 500
    MinimumWidth 200
    Shadowing 1
}
rootNode {
    Shadowing 0
}

</style>

* Trabalhador Médio Brasileiro
**:**Pensa e sente**
* Preciso estar no trabalho logo (a tempo)
* Com certa frequência os estacionamentes estão lotados, principalmente em horários de pico e datas de compras
* Por que não podemos parar logo?
* Este trânsito está uma bagunça
;

**:**Ver**
    * Diversos preços diferentes.
    * Pessoas procurando estacionar em ruas.
    * Dificuldade para encontrar estacionamento perto do seu local de destino.
    * Estacionamentos com estrutura não apropriada
;

left side

**:**Fala e faz**
    * Não sei onde posso ou não estacionar
;

**:**Ouve**
;


@endmindmap